# Generated by Django 4.2.5 on 2025-03-08 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Protein",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_id", models.CharField(max_length=512, unique=True)),
                ("uniprot_id", models.CharField(max_length=512)),
                ("uniprot_description", models.CharField(max_length=512)),
                ("uniprot_sequence", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProteinResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alphafold_result", models.FileField(upload_to="")),
                ("quantum_result", models.FileField(upload_to="")),
                (
                    "protein",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.protein"
                    ),
                ),
            ],
        ),
    ]
