# Generated by Django 5.1.7 on 2025-03-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_user_managers_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protein",
            name="uniprot_id",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
